<p>
CIFF Impact Portal shows the map of countries and regions where CIFF-funded programmes are implemented and evaluated.
</p>

<h6>Standard Operating Procedure</h6>
<ul>
<li>Select a country by clicking any highlighted region on the map. CIFF investment(s) in this country will be listed on the top right panel. The number of evaluations per country is displayed on the map.</li>
<li>Click any investment to see further information.
<ul>
<li>Some investments contain geo-coordinate of the locations related to the investments. For such investment, a link is provided in <b>Region</b> row to show the locations on the map.</li>
<li>Some investments are implemented in multiple countries. For such investment, a link is provided in <b>Region</b> row to show those countries.</li>
</ul>
</li>
<li>Filtering by <b>Country</b>, <b>Sector</b>, <b>Target Population</b>, and/or <b>Primary Outcome</b> can also be done using the top-left panel. Click <kbd>Reset</kbd> to clear/reset the filter.</li>
<li>Click <span class='fa fa-cog'></span> to perform additional setting to the map, such as toggle country labels, map scale, and auto-zoom functionality.</li>
</ul>

<h6>Disclaimer</h6>
<p>Maps used on this website are for general illustration only, and are not intended to be used for reference purposes. The representation of political boundaries does not necessarily reflect the organization's view on the legal status of a country or territory.
</p>

<h6>Acknowledgement</h6>
<ul>
<li>India Administrative Boundaries were sourced from: Ministry of Science and Technology, Government of India. Survey of India. Online Maps Portal. Administrative Boundary Database (<a href='https://onlinemaps.surveyofindia.gov.in/Digital_Product_Show.aspx' target='_blank'>OVSF/1M/7</a>).
</li>

<li>Nigeria Administrative Boundaries were sourced from: eHealth Africa and Proxy Logics (2020). Nigeria Operational State Boundaries. Geo-Referenced Infrastructure and Demographic Data for Development <a href='https://grid3.gov.ng/' target='_blank'>GRID3</a>.
</li>

<li>The administrative boundaries for the remaining countries were sourced from <a href='https://geoboundaries.org' target='_blank'>geoboundaries.org</a> (<a href='https://doi.org/10.1371/journal.pone.0231866' target='_blank'>Rufalo et al., 2020</a>).
</li>
</ul>

<p>This web portal was developed by the Spatial Data Infrastructure (SDI) Team at WorldPop. The work is funded by the Children's Investment Fund Foundation (CIFF)
</p>